CREATE DATABASE IF NOT EXISTS HOTEL_MPC;


CREATE TABLE HOTEL_MPC.TBL_REGION (
    ID_REGION INT PRIMARY KEY NOT NULL,
    NOMBRE_REGION VARCHAR(50),
    DESCRIPCION_REGION VARCHAR(50)
);

CREATE TABLE HOTEL_MPC.TBL_PROVINCIAS (
    ID_PROVINCIA INT PRIMARY KEY NOT NULL,
    ID_REGION INT NOT NULL,
    NOMBRE_PROVINCIA VARCHAR(50),
    DESCRIPCION_PROVINCIA VARCHAR(50),
    FOREIGN KEY (ID_REGION) REFERENCES TBL_REGION(ID_REGION)
);

CREATE TABLE HOTEL_MPC.TBL_COMUNAS (
    ID_COMUNA INT PRIMARY KEY NOT NULL,
    ID_PROVINCIA INT NOT NULL,
    NOMBRE_COMUNA VARCHAR(50) NOT NULL,
    DESCRIPCION_COMUNA VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_PROVINCIA) REFERENCES TBL_PROVINCIAS(ID_PROVINCIA)
);

CREATE TABLE HOTEL_MPC.TBL_TIPO_CAMA (
    ID_TIPO_CAMA INT AUTO_INCREMENT PRIMARY KEY,
    TIPO_CAMA VARCHAR(50) NOT NULL
);

CREATE TABLE HOTEL_MPC.TBL_ORIENTACION (
    ID_ORIENTACION INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(100) NOT NULL
);

CREATE TABLE HOTEL_MPC.TBL_ESTADO_HABITACION (
    ID_ESTADO_HAB INT AUTO_INCREMENT PRIMARY KEY,
    ESTADO_HAB VARCHAR(50) NOT NULL
);

CREATE TABLE HOTEL_MPC.TBL_ESTADO_RESVERVA (
    ID_ESTADO_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    ESTADO_RESV VARCHAR(50) NOT NULL
);

CREATE TABLE HOTEL_MPC.TBL_USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CONTRASENA VARCHAR(100) NOT NULL,
    ES_ADMINISTRADOR BOOLEAN NOT NULL
);

/**************************************/

CREATE TABLE HOTEL_MPC.TBL_HABITACION (
    ID_HABITACION INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO_HABITACION INT NOT NULL,
    CAPACIDAD INT NOT NULL,
    ID_TIPO_CAMA INT,
    ID_ORIENTACION INT,
    ID_ESTADO_HAB INT,
    FOREIGN KEY (ID_TIPO_CAMA) REFERENCES HOTEL_MPC.TBL_TIPO_CAMA(ID_TIPO_CAMA),
    FOREIGN KEY (ID_ORIENTACION) REFERENCES HOTEL_MPC.TBL_ORIENTACION(ID_ORIENTACION),
    FOREIGN KEY (ID_ESTADO_HAB) REFERENCES HOTEL_MPC.TBL_ESTADO_HABITACION(ID_ESTADO_HAB)
);

CREATE TABLE HOTEL_MPC.TBL_RESERVA (
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    FEC_RESERVA DATE NOT NULL,
    FEC_LLEGADA DATE NOT NULL,
    FEC_SALIDA DATE NOT NULL,
    CANT_PASAJEROS INT NOT NULL,
    MONTO_TOTAL DECIMAL(10, 2) NOT NULL,
    ID_ESTADO_RESERVA INT,
    PENALIZACION DECIMAL(10, 2),
    ID_HABITACION INT,
    FOREIGN KEY (ID_ESTADO_RESERVA) REFERENCES HOTEL_MPC.TBL_ESTADO_RESVERVA(ID_ESTADO_RESERVA),
    FOREIGN KEY (ID_HABITACION) REFERENCES HOTEL_MPC.TBL_HABITACION(ID_HABITACION)
);


CREATE TABLE HOTEL_MPC.TBL_PASAJERO (
    ID_PASAJERO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    FEC_NACIMIENTO DATE NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    ID_REGION INT,
    ID_PROVINCIA INT,
    ID_COMUNA INT,
    FOREIGN KEY (ID_REGION) REFERENCES HOTEL_MPC.TBL_REGION(ID_REGION),
    FOREIGN KEY (ID_PROVINCIA) REFERENCES HOTEL_MPC.TBL_PROVINCIAS(ID_PROVINCIA),
    FOREIGN KEY (ID_COMUNA) REFERENCES HOTEL_MPC.TBL_COMUNAS(ID_COMUNA)
);

CREATE TABLE HOTEL_MPC.TBL_RESERVA_PASAJERO (
    ID_RESERVA_PASAJERO INT AUTO_INCREMENT PRIMARY KEY,
    ID_RESERVA INT,
    ID_PASAJERO INT,
    COSTO_PASAJERO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_RESERVA) REFERENCES HOTEL_MPC.TBL_RESERVA(ID_RESERVA),
    FOREIGN KEY (ID_PASAJERO) REFERENCES HOTEL_MPC.TBL_PASAJERO(ID_PASAJERO)
);


CREATE TABLE HOTEL_MPC.TBL_USUARIO_ADMIN (
    ID_USUARIO_ADMIN INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES HOTEL_MPC.TBL_USUARIO (ID_USUARIO)
);