/* Alter por Normalizacion */


-- hotel_mpc.tbl_usuario
ALTER TABLE hotel_mpc.tbl_usuario
RENAME COLUMN NOMBRE TO USER_NOMBRE,
RENAME COLUMN APELLIDO TO USER_APELLIDO, 
RENAME COLUMN EMAIL TO USER_EMAIL;


--hotel_mpc.tbl_pasajero
ALTER TABLE hotel_mpc.tbl_pasajero
RENAME COLUMN NOMBRE TO NOMBRE_PASAJERO,
RENAME COLUMN APELLIDOS TO APELLIDO_PASAJERO, 
RENAME COLUMN FEC_NACIMIENTO TO FEC_NAC_PASAJERO
RENAME COLUMN CORREO TO USER_EMAIL_PASAJERO,
RENAME COLUMN DIRECCION TO DIRE_PASAJERO;